### ISSUE TITLE
Question: I am trying to understand why you are defining clayer.yml instead of using components from packs/cloned repos

### ISSUE THREAD

**Issue by jkrech** [W-MINE/RTX5-QuickStart-STM32F4#1]
In case you want to use "local" packs that are in your workspace you can specify e.g. in your standard_edition.cproject.yml file:
To replace the DSP clayer:
```
  packs:
    - pack: ARM::CMSIS-DSP
      path: ../../../Drivers/CMSIS-DSP

  components:
    - component: ARM::CMSIS:DSP&Source

...
   # - layer: ../layer/cmsis-dsp.clayer.yml
...

```
